// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID        int32            `json:"id"`
	Amount    string           `json:"amount"`
	Reason    *string          `json:"reason"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Type      *string          `json:"type"`
}
