// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetTransactionByID(ctx context.Context, id int32) (GetTransactionByIDRow, error)
	GetTransactions(ctx context.Context) ([]GetTransactionsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
}

var _ Querier = (*Queries)(nil)
