// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: transactions.sql

package sqlc

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (amount, reason, type) VALUES ($1, $2, $3) RETURNING id, amount, reason, created_at, type
`

type CreateTransactionParams struct {
	Amount string  `json:"amount"`
	Reason *string `json:"reason"`
	Type   *string `json:"type"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction, arg.Amount, arg.Reason, arg.Type)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Reason,
		&i.CreatedAt,
		&i.Type,
	)
	return i, err
}

const getTransactions = `-- name: GetTransactions :many
SELECT id, amount, reason, created_at, type FROM transactions
`

func (q *Queries) GetTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Reason,
			&i.CreatedAt,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
