// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"
	"time"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (amount, type, reason, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, amount, type, reason, created_at, user_id
`

type CreateTransactionParams struct {
	Amount string  `json:"amount"`
	Type   *string `json:"type"`
	Reason *string `json:"reason"`
	UserID *int32  `json:"user_id"`
}

type CreateTransactionRow struct {
	ID        int32     `json:"id"`
	Amount    string    `json:"amount"`
	Type      *string   `json:"type"`
	Reason    *string   `json:"reason"`
	CreatedAt time.Time `json:"created_at"`
	UserID    *int32    `json:"user_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Amount,
		arg.Type,
		arg.Reason,
		arg.UserID,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Type,
		&i.Reason,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, amount, type, reason, created_at, user_id 
FROM transactions
WHERE id = $1
`

type GetTransactionByIDRow struct {
	ID        int32     `json:"id"`
	Amount    string    `json:"amount"`
	Type      *string   `json:"type"`
	Reason    *string   `json:"reason"`
	CreatedAt time.Time `json:"created_at"`
	UserID    *int32    `json:"user_id"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, id int32) (GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Type,
		&i.Reason,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getTransactions = `-- name: GetTransactions :many
SELECT id, amount, type, reason, created_at, user_id 
FROM transactions
ORDER BY created_at DESC
`

type GetTransactionsRow struct {
	ID        int32     `json:"id"`
	Amount    string    `json:"amount"`
	Type      *string   `json:"type"`
	Reason    *string   `json:"reason"`
	CreatedAt time.Time `json:"created_at"`
	UserID    *int32    `json:"user_id"`
}

func (q *Queries) GetTransactions(ctx context.Context) ([]GetTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionsRow{}
	for rows.Next() {
		var i GetTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Type,
			&i.Reason,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
